### ISSUE TITLE
Plugin breaks on Vite 2.7.0.

### ISSUE THREAD

**Issue by james-camilleri** [poppa/sveltekit-svg#11]
There have been some (minor) breaking changes to Vite on the latest version. The API has changed, as detailed here - https://github.com/vitejs/vite/blob/v2.7.1/packages/vite/CHANGELOG.md#270-2021-12-07. I've created a small PR that should fix it. #10

**Comment by poppa** [comment]
Fixed in v.0.2.2. Thanks for the PR 👍

**Comment by james-camilleri** [comment]
Not at all, thanks for merging so quickly! 😁
