### ISSUE TITLE
Property X does not exist on type 'IntrinsicAttributes'

### ISSUE THREAD

**Issue by chiubaca** [poppa/sveltekit-svg#13]
Thanks for this plugin, it's working great.

However  when passing any attributes  e.g `color` ,`height` etc,  I get a TS error:

```
Property `x` does not exist on type 'IntrinsicAttributes'
```

![image](https://user-images.githubusercontent.com/18376481/147753172-66e5198f-81f5-4364-bafa-b0de7c867de3.png)

currently using:
```
"@sveltejs/kit": "1.0.0-next.1",
"svelte": "^3.44.0",
"typescript": "^4.4.3"
```

**Comment by poppa** [comment]
Thanks for your bug report @chiubaca!

I'm not 100% sure this can be solved by the plugin itself, the reason being that this is determined by where and how VSCode (or any editor using a language server and the language server protocol I guess) resolves the module definition for SVGs.

There are many other plugins/modules providing type definitions for SVGs and those can clash with each other so the editor can be confused over which to use. This is at least my understanding of the problem.

One solution you can try is adding `?component` to your import:

```svelte
<script lang="ts">
import PauseIcon from './pause-icon.svg?component'
</script>

<PauseIcon color="green" />
```

This may or may not require that you copy `global.d.ts` (or its content) from this package to the root or source of you project and make sure its path is included in your `tsconfig.json`.

Let me know if this helps.

**Comment by chiubaca** [comment]
Thanks for the response @poppa.  I tried appending `?component`  and I've added the following to my `global.d.ts` in the root of my project:


```ts
declare module '*.svg' {
	import { SvelteComponent } from 'svelte';
	const content: SvelteComponent;
	// @ts-expect-error
	// vite/client.d.ts defines this as "string"
	export default content;
}

declare module '*.svg?component' {
	import { SvelteComponent } from 'svelte';
	const content: SvelteComponent;
	export default content;
}

declare module '*.svg?src' {
	const content: string;
	export default content;
}

declare module '*.svg?url' {
	const content: string;
	export default content;
}

```

But now i'm seeing a different error ...

```
JSX element type 'PauseIcon' does not have any construct or call signatures.js(2604)
```

**Comment by poppa** [comment]
Ok, then the solution is to scrap the `SvelteComponent` type and simply replace it with `any` and your error/warning will go away.

```ts
declare module '*.svg?component' {
	const content: any;
	export default content;
}
```

I’ll take a more thorough look at this when I get the time.
