### ISSUE TITLE
Allow passing resvg variable via options to allow different plugins per path

### ISSUE THREAD

**Issue by ljani** [poppa/sveltekit-svg#16]
Please consider adding a way to pass [`resvg`](https://github.com/poppa/sveltekit-svg/blob/7a75e525d5b23bc042a90f2a3133965f37cd5961/src/index.ts#L31) regex via [`Options`](https://github.com/poppa/sveltekit-svg/blob/7a75e525d5b23bc042a90f2a3133965f37cd5961/src/index.ts#L6-L9) to allow different plugins to be applied per path.

My use case is that I want to apply eg. [`removeAttrs`](https://github.com/svg/svgo/blob/da1d761b53c97cd7053b5370cb32c30e7e4978d4/plugins/removeAttrs.js) with `attrs: "(fill|stroke)"` to icons, but leave some full color SVG files alone.

**Comment by poppa** [comment]
Thanks for your feedback @ljani 

Can you please give me a more elaborate example of how you'd want to use this?

**Comment by ljani** [comment]
Sure.

As the quickest hack, something like this:

```ts
import svg from "@poppanator/sveltekit-svg";

const config = {
  kit: {
    vite: {
      plugins: [
        svg({
          resvg: /[\\/]icons[\\/].*\.svg(?:\?(src|url|component))?$/,
          svgoOptions: {
            multipass: true,
            plugins: ["preset-default", { name: "removeAttrs", params: { attrs: "(fill|stroke)" }}],
          },
        }),
        svg({
          resvg: /[\\/]graphics[\\/].*\.svg(?:\?(src|url|component))?$/,
          svgoOptions: {
            multipass: true,
            plugins: ["preset-default" ],
          },
        }),
      ],
    },
  },
};
```

A better alternative would probably be a separate option such as:

```ts
import svg from "@poppanator/sveltekit-svg";

const config = {
  kit: {
    vite: {
      plugins: [
        svg({
          includePaths: ["./src/lib/icons/"],
          svgoOptions: {
            multipass: true,
            plugins: ["preset-default", { name: "removeAttrs", params: { attrs: "(fill|stroke)" }}],
          },
        }),
        svg({
          includePaths: ["./src/lib/graphics/"],
          svgoOptions: {
            multipass: true,
            plugins: ["preset-default" ],
          },
        }),
      ],
    },
  },
};
```

Does this clear up my use case?

Please note that `includePaths` should also support a backslash (`\`) as path separator in addition to forward slash (`/`).

**Comment by poppa** [comment]
@ljani Theres a beta version you can test if you want: 
https://www.npmjs.com/package/@poppanator/sveltekit-svg/v/0.2.4-0

I haven't tested it widely, and I have no idea if it works properly on Windows for instance. But give it a go and see if it comes close to your expectation.

Thanks.

**Comment by ljani** [comment]
Great, thanks! It seems to fine work on Windows as well.

To be honest, I meant a simpler solution, such as `includePaths` being path prefixes, which are checked (see eg. [`svelte-preprocess-cssmodules`](https://github.com/micantoine/svelte-preprocess-cssmodules/blob/5fec4c65e8180b261bfdabcd5d139851ff928970/src/lib/requirement.ts#L31), however be sure to normalize path separators), but globbing works fine as well 😊 For example `webpack` uses regexes, if you'd like to avoid another dependency.

**Comment by poppa** [comment]
Thanks @ljani, I tend to agree. As few dependencies as possible, and in this particular case I don't think the globbing adds any real value anyway. I'll make an update...

**Comment by poppa** [comment]
A new  **beta** version published: https://www.npmjs.com/package/@poppanator/sveltekit-svg/v/0.2.4-1

**Comment by ljani** [comment]
@poppa: Thanks. However, that version does not work on Windows. [`path.normalize`](https://nodejs.org/api/path.html#pathnormalizepath) will return backslashes on Windows and `id` will be with forward slashes. For example, `id` is `C:/devel/mysite/src/lib/gfx/logo.svg?component` and `includePath` is `C:\devel\hoijan-site\src\lib\gfx` and thus `string.startsWith` will fail.

**Comment by ljani** [comment]
@poppa: I saw your https://github.com/poppa/sveltekit-svg/commit/e0dad5fc78cfbff712b10ff7f895f4666dc2a1de while fetching upstream 🙂 That won't work either, here's me logging `id` and `includePath`:

```text
C:/devel/mysite/src/lib/gfx/logo.svg?component -> /devel/mysite/src/lib/gfx
```

**Comment by poppa** [comment]
Yes, I noticed @ljani . I've got a Windows VirtualBox instance running now. I've merged your PR:s, so it seems it's all good to go.

**Comment by ljani** [comment]
Tested via `npm install --save github:ljani/sveltekit-svg#4b5128e3ac34cf020b35cc7f4cb09d28499e6dd3` and everything seems to be working. I could not test directly from this repo because of [missing `prepare` script](https://github.com/ljani/sveltekit-svg/commit/4b5128e3ac34cf020b35cc7f4cb09d28499e6dd3). I just learnt that from [StackOverflow](https://stackoverflow.com/a/57829251/706690).

Feel free to close the issue, thanks again!

**Comment by poppa** [comment]
Thanks for you help 🥇
