### ISSUE TITLE
SSR true

### ISSUE THREAD

**Issue by nosovk** [poppa/sveltekit-svg#31]
<img width="848" alt="image" src="https://user-images.githubusercontent.com/1398808/217370607-fadf9434-bc4e-45fc-9c22-7b75c0bf14c8.png">
It seems that in SSR mode generated component if we use `?component` syntax fails

**Comment by poppa** [comment]
I need more context. What do you explicitly mean by SSR-mode? What version of Svelte-Kit are you running?

**Comment by poppa** [comment]
Lol, I accidentally closed the issue 😂

**Comment by nosovk** [comment]
I mean SvelteKIT app with enabled SSR (I used latest kit with Cloud flare pages adapter)
When I used component in SPA mode - everting works correct, but in SSR mode - have an error as the one above,
https://kit.svelte.dev/docs/adapter-static#spa-mode

**Comment by poppa** [comment]
Is the `<TikTok>`-component from a different NPM package (library)? In that case it doesn't work. It's explained in issue #23

**Comment by nosovk** [comment]
Sorry, I didn't explained in first message, <TikTok> is a name of SVG icon to import as component

**Comment by poppa** [comment]
I think the easiest way, since I can't reproduce this myself, is for you to create a GitHub repo I can fork with the problem as isolated as possible. Because I need to see some code and configuration to possibly figure out what your problem is.

**Comment by poppa** [comment]
Feel free to re-open this issue if you provide information that can make me reproduce this problem.
