### ISSUE TITLE
Support alternative datauri encodings

### ISSUE THREAD

**Issue by c6p** [poppa/sveltekit-svg#32]
svgo has a `datauri` option to set the encoding: `base64`, `enc` (URI encoded), `unenc`. See https://github.com/svg/svgo/issues/105.
Though, before v3 `datauri` field sometimes seems to be ignored: https://github.com/svg/svgo/pull/1679 

This plugin currently only support base64. Could you honour the "datauri" field in optimization config?

**Comment by poppa** [comment]
I will take a look at it in the near future 👍

**Comment by poppa** [comment]
This should now be fixed in the latest version. Note that this issued a new major version since this feature required a version bump of the SVGO dependency to >=3.0.

Feel free to reopen this issue if this new feature doesn't work as expected.
