### ISSUE TITLE
Svelte 4 support

### ISSUE THREAD

**Issue by ShadiestGoat** [poppa/sveltekit-svg#36]
Since svelte 4 was released as a stable module, it would be lovely to update this project to svelte 4. Due to this being a relatively small upgrade, there shouldn't be too many complications. I *think* this package would probably just require a version bump in the `package.json`

[Related migration guide](https://svelte.dev/docs/v4-migration-guide)

Thank you for the kind work!

**Comment by poppa** [comment]
Thanks. @poppanator/sveltekit-svg@4 should have this fixed
