### ISSUE TITLE
Import SVG component dynamically based on input that the component is getting

### ISSUE THREAD

**Issue by ambigos1** [poppa/sveltekit-svg#37]
Hi.
I would like to add svg icon dynamically based on parameters that the component is getting by its inputs.

Input example:
socials: [
			{ link: 'XXX', url: '../images/icons/instagram-brands.svg' },
			{ link: 'XXX', url: '../images/icons/tiktok-brands.svg' },
			{ link: 'XXX', url: '../images/icons/whatsapp-brands.svg' },
			{ link: 'https://t.me/InstBlast', url: '../images/icons/telegram-plane-brands.svg' }
		]

I tried dynamic import like the example above but the icons is not displayed

      {#each data.socials as social }
        <a
          href={social.link}
          target="_blank"
          rel="noopener noreferrer"
          class="text-gray-400 hover:text-gray-900 hover:text-primary"
        >
          {#await import(`${social.url}?component`) then Icon}
            <Icon.default width="200" />
          {/await}
        </a>
      {/each}

Any suggestions How can I make it work?

Thanks.

**Comment by poppa** [comment]
This is a build-time plugin and dynamic imports are runtime, so I can't see this would ever work.
