### ISSUE TITLE
Using SVG as component is giving me an error?

### ISSUE THREAD

**Issue by hypercompl3x** [poppa/sveltekit-svg#38]
Don't think I am doing anything wrong? 

![image](https://github.com/poppa/sveltekit-svg/assets/45500254/7b263ebf-b2d1-4453-97bf-10aa5c560122)

![image](https://github.com/poppa/sveltekit-svg/assets/45500254/6202409d-c298-4dde-bf0e-d15d3a49e553)

![error](https://github.com/poppa/sveltekit-svg/assets/45500254/53b8aa2c-4670-46c4-82e9-3267d915433a)

**Comment by poppa** [comment]
It would help a lot if you could state what versions you are using, primarily Svelte/SvelteKit, Vite, @poppanator/sveltekit-svg.

**Comment by hypercompl3x** [comment]
"@sveltejs/kit": "^1.20.4",
"svelte": "^4.0.0",
"@poppanator/sveltekit-svg": "^4.0.0",
"vite": "^4.3.6",

**Comment by poppa** [comment]
Note that the plugin should be in `vite.config` and not `svelte.config`
