### ISSUE TITLE
`Error: Cannot find module 'svgo'`

### ISSUE THREAD

**Issue by jerrygreen** [poppa/sveltekit-svg#46]
I did `yarn add --dev @poppanator/sveltekit-svg`
I added `import svg from '@poppanator/sveltekit-svg'` and used as plugin:
`plugins: [sveltekit(), svg()]`

After that, I'm trying to run `yarn dev` and this error happens.

```
yarn dev
yarn run v1.22.4
$ vite dev
failed to load config from C:\Users\Jerry\projects\jerrygreen.github.io-src2\vite.config.ts
error when starting dev server:
Error: Cannot find module 'svgo'
```

Is this a dependency I should manually add, or?

**Comment by poppa** [comment]
Indeed, `svgo` is a `peerDependency` and those the consumer (you) need to install explicitly.

So `yarn add --dev svgo` will probably solve the problem.

**Comment by jerrygreen** [comment]
Indeed, it solved the issue.
I guess you should add it to readme though

**Comment by poppa** [comment]
I'm pretty sure Yarn told you you had an unmet peer dependency when installing the plugin.

**Comment by jerrygreen** [comment]
Indeed. On the second thought, if it's required to use this library for the most simplest cases, why make it peer dependency? IMO it should be normal dependency.

**Comment by Bowis** [comment]
Agreeing with @jerrygreen here. Literally every package out there says: "Make sure to install X as well". The time spent on this issue could have easily been used to add it to the readme 🤷
