### ISSUE TITLE
 Sourcemap issues

### ISSUE THREAD

**Issue by drFerg** [poppa/sveltekit-svg#48]
Hi thanks for creating this great little package.

I noticed this warning in our builds when using with a typical svelte + kit + vite build.

```
(sveltekit-svg plugin) Sourcemap is likely to be incorrect: a plugin (sveltekit-svg) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
```
Are we missing something in our config or is this possibly an issue with the plugin?

Happy to provide any other details if useful.
Thanks!

**Comment by poppa** [comment]
Hi @drFerg! 

I really can't say why you get that warning. I can't reproduce it just by creating a brand new Svelte Kit app, and I haven't had any prior bug report like this. So unfortunately I can't get you any clues from the top of my head.

I'm guessing this has something to do with some combination of plugins and/or packages, so we'll need to investigate a bit.

1. What versions are you running (Svelte, Vite, @poppanator/sveltekit-svg)
2. If possible, share your config file.
3. If possible, reduce the problem to an as simple as possible standalone project and create a repo for it so I can clone it.

**Comment by poppa** [comment]
Actually, I got it myself in a project just now. I think I might have a fix for it on the way ...

**Comment by poppa** [comment]
Alright, give `v4.1.2` a shot and see if that solves the issue?

**Comment by drFerg** [comment]
Hey, thanks for that. It looks like that resolved most of the messages I was getting (about 40) - I get about 1/4 of them now. It looks like that fixed one of the branches but perhaps one of the other branches is missing it?

**Comment by poppa** [comment]
Alright, give `4.1.3` a shot and see if that solves it.

What annoys the hell out of me is that I can't reliably reproduce it in the test-app I use, but this seemed to fix it in the real world app I have in which I could see the same warning.

**Comment by poppa** [comment]
Feel free to reopen this issue if the problem persists @drFerg
