### ISSUE TITLE
Get SVGSVGElement from generated component

### ISSUE THREAD

**Issue by capsey** [poppa/sveltekit-svg#49]
When getting a component using `*.svg?component` is there a way to get an instance of `SVGSVGElement` from the component? Like what `bind:this` does on the `<svg>` tag (and all the other DOM element tags). Alternatively, is there a way to add `use:action` to the element or any other way to access lifetime hooks?

**Comment by poppa** [comment]
`use:action` is only applicable on DOM nodes and not on Svelte Components. Likewise `bind:this` on a component will bind the component instance and not any potential DOM node that component might output.

You might be able to accomplish what you ask for with the [`preCompileHook()`](https://github.com/poppa/sveltekit-svg#options), in which you can generate the resulting Svelte Component yourself.

Hope that helps!

**Comment by poppa** [comment]
Feel free to reopen this issue if you have any further questions @capsey
