### ISSUE TITLE
Pass attributes to Svelte components

### ISSUE THREAD

**Issue by vabatta** [poppa/sveltekit-svg#5]
Hi,

I was wondering if it would be possible to pass attributes to the SVG when loaded as Svelte components.
For example:
```svelte
<script>
import FacebookLogo from 'line-awesome/svg/facebook-f.svg';
</script>

<FacebookLogo class="my-class" />
```

**Comment by poppa** [comment]
I will take a look at it in the coming days 👍

**Comment by poppa** [comment]
@vabatta I don't know if this is such a good idea. I think it will be difficult to manage this in an efficient way since you need to parse all attributes in the SVG to merge the values if the attribute passed from the Svelte component already exists in the SVG node. Take your `class` attribute for example: It's not unthinkable that an SVG already has a `class` attribute. 

What I usually do is wrapping the SVG so I can style it from the parent node:

```svelte
<div class="svg-wrapper">
  <MySvg />
</div>

<style>
.svg-wrapper {
  :global(svg) {
    // svg style
  }
}
</style>
```

Let me know if you have a good argument for forwarding attributes to the SVG and I will reconsider 👍

**Comment by vabatta** [comment]
I would leave the job of making sure `class` and `attributes` don't clash to the developer, honestly. For example, you as a developer might know that the `svg` being used in a certain context have a `fill` attribute which makes useless a class that changes the color (unless `fill="currentColor"`). Also, when it comes to `class` merging is more about the stylesheet generation order that makes the classes get applied to the SVG; which again is the dev job to make sure they are the right order for what you need (I am thinking of Tailwind that does the job for you already :) ). 
Finally, for merging prop classes and SVG ones, I would use a [tiny runtime library (228B!)](https://www.npmjs.com/package/clsx) to not have other implementation laying around.

**Comment by AradAral** [comment]
Hi @poppa, I expected this to have already been implemented honestly.
Why can't this be done like [vite-plugin-svelte-svg](https://github.com/metafy-gg/vite-plugin-svelte-svg) does it?

**Comment by AradAral** [comment]
> since you need to parse all attributes in the SVG to merge the values if the attribute passed from the Svelte component already exists

You don't, just put {...props} after all the attributes and the user-defined attributes will take precedence, Svelte already takes care of that for every element.

**Comment by AradAral** [comment]
@poppa Would you like me to create a PR for this?

**Comment by poppa** [comment]
Hi @AradAral. You are more than welcome to create a PR 👍

**Comment by Tropix126** [comment]
> > since you need to parse all attributes in the SVG to merge the values if the attribute passed from the Svelte component already exists
> 
> You don't, just put `{...props}` after all the attributes and the user-defined attributes will take precedence, Svelte already takes care of stuff like that.

`{...$$restProps}`* in this case

**Comment by AradAral** [comment]
@Tropix126 Well, `{...$$restProps}` is for when your component itself has props. In this case the component doesn't have any props. Does it?
So the `$$props` and `$$restProps` would be the same here.

**Comment by AradAral** [comment]
Thank you @poppa for implementing this!
