### ISSUE TITLE
Not a valid SSR component

### ISSUE THREAD

**Issue by cristianvogel** [poppa/sveltekit-svg#50]
Hi! 

I would like to use the Component style rendering import, but I get this error in my project. 

`Error: <BackgroundSvg> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules. Otherwise you may need to fix a <BackgroundSvg>.
    at Module.validate_component `

i am on 
```
   "svelte": "^4.2.0",
    "svelte-check": "^3.4.6",
"@sveltejs/adapter-auto": "^2.1.0",
    "@sveltejs/adapter-vercel": "^3.0.3",
    "@sveltejs/kit": "^1.5.0",
```

**Comment by cristianvogel** [comment]
> Hi!
> 
> I would like to use the Component style rendering import, but I get this error in my project.
> 
> `Error: <BackgroundSvg> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules. Otherwise you may need to fix a <BackgroundSvg>. at Module.validate_component `
> 
> i am on
> 
> ```
>    "svelte": "^4.2.0",
>     "svelte-check": "^3.4.6",
> "@sveltejs/adapter-auto": "^2.1.0",
>     "@sveltejs/adapter-vercel": "^3.0.3",
>     "@sveltejs/kit": "^1.5.0",
> ```

I don't want to mess around with reviewing the build config...

**Comment by poppa** [comment]
Hi @cristianvogel. 

This unfortunately doesn't help me very much. 

Might your problem be due to a [misconfiguration like this](https://github.com/poppa/sveltekit-svg/issues/33#issuecomment-1654747909)?

**Comment by cristianvogel** [comment]
Hi ... I got the component style working. Seems like I had a mixture of Path config mistake ( forgetting the trailing slash ) and an invalid attribute jarring the SVGO parser. Which summarised to a 'not a valid SSR component'
