### ISSUE TITLE
This svg does not work when imported as component or src, but does when used used directly

### ISSUE THREAD

**Issue by jakubdonovan** [poppa/sveltekit-svg#56]
```
<svg width="916" height="1001" viewBox="0 0 916 1001" fill="none" xmlns="http://www.w3.org/2000/svg">
   <g filter="url(#filter0_f_549_57)">
      <rect x="300" y="300" width="316" height="401" fill="url(#paint0_linear_549_57)" />
   </g>
   <defs>
      <filter id="filter0_f_549_57" x="0" y="0" width="916" height="1001" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
         <feFlood flood-opacity="0" result="BackgroundImageFix" />
         <feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape" />
         <feGaussianBlur stdDeviation="150" result="effect1_foregroundBlur_549_57" />
      </filter>
      <linearGradient id="paint0_linear_549_57" x1="431" y1="1328" x2="458.523" y2="300" gradientUnits="userSpaceOnUse">
         <stop stop-color="#4F46E5" />
         <stop offset="1" stop-color="#472187" />
      </linearGradient>
   </defs>
</svg>
```
```
import BlurComponent from '$lib/assets/blur.svg?component';
import BlurSrc from '$lib/assets/blur.svg?src';
	
<BlurComponent />
{@html BlurSrc}
<svg width="916" height="1001" viewBox="0 0 916 1001" fill="none" xmlns="http://www.w3.org/2000/svg">
	<g filter="url(#filter0_f_549_57)">
		<rect x="300" y="300" width="316" height="401" fill="url(#paint0_linear_549_57)" />
	</g>
	<defs>
		<filter id="filter0_f_549_57" x="0" y="0" width="916" height="1001" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
		        <feFlood flood-opacity="0" result="BackgroundImageFix" />
		       <feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape" />
		        <feGaussianBlur stdDeviation="150" result="effect1_foregroundBlur_549_57" />
		</filter>
		<linearGradient id="paint0_linear_549_57" x1="431" y1="1328" x2="458.523" y2="300" gradientUnits="userSpaceOnUse">
			<stop stop-color="#4F46E5" />
			<stop offset="1" stop-color="#472187" />
		</linearGradient>
	</defs>
</svg>

```
![Screenshot 2024-04-08 at 16 09 32](https://github.com/poppa/sveltekit-svg/assets/16073448/9949ba4b-ffc7-4343-87c5-541a8d91d519)

**Comment by jakubdonovan** [comment]
I didn't pass any options to the plugin either and just use the default and the svg doesn't work. Can you show me?

**Comment by poppa** [comment]
There’s a reference to a commit in this thread.

# Sent while in motion

**Comment by jakubdonovan** [comment]
> #56



> There’s a reference to a commit in this thread. # Sent while in motion

I'm still struggling to get this to work. The SVG seems to work fine in some elements but doesn't blur in others. I think that it might have something to do with SVGO cleaning up the IDs, though I'm not sure why that would be the case as each svg is its own component so there should be no interference with IDs anywhere else on the page. Anyway, I'm trying to test it without cleaning up the ids but I can't seem to disable that option
`svg({
	svgoOptions: {
		cleanupIDs: false
	}
})`
"Object literal may only specify known properties, and 'cleanupIDs' does not exist in type 'Config'.ts(2353)"

**Comment by poppa** [comment]
> I'm still struggling to get this to work. [...]. I think that it might have something to do with SVGO cleaning up the IDs, though I'm not sure why that would be the case as each svg is its own component so there should be no interference with IDs anywhere else on the page. 

Well, that's not entirely true. Albeit they are their own components, but they are just rendered inline in the resulting HTML, and thus SVGs with the same IDs will conflict. 

I think there is an "id-prefix" plugin for SVGO to solve problemes like this.

**Comment by poppa** [comment]
@jakubdonovan Have you solved your problem? Can this issue be closed?

**Comment by jakubdonovan** [comment]
Yes, prefixing ids was the better solution.
