### ISSUE TITLE
svelte5 next.183 issues with passing props

### ISSUE THREAD

**Issue by sansjack** [poppa/sveltekit-svg#59]
Hey all, since upgrading my svelte5 I'm getting these error on my exported SVG components:

```ts
Type '{ class: string; }' is not assignable to type 'Properties<SvelteComponent<SVGAttributes<SVGSVGElement>, any, any>, any>'.
```

being used like this:
```ts
import GoogleIcon from './google.svg?component' // const GoogleIcon: Component<SvelteComponent<SVGAttributes<SVGSVGElement>, any, any>, {}, string>

export { GoogleIcon }
```
example of error when using the component: 
```js
<GoogleIcon class="size-6" /> //Type '{ class: string; }' is not assignable to type 'Properties<SvelteComponent<SVGAttributes<SVGSVGElement>, any, any>, any>'.
```

current package versions: 
- `"@poppanator/sveltekit-svg": "^5.0.0-svelte5.4"`
- `"svelte": "^5.0.0-next.183"`

**Comment by sansjack** [comment]
#60

**Comment by poppa** [comment]
There's a new [pre-release available](https://www.npmjs.com/package/@poppanator/sveltekit-svg/v/5.0.0-svelte5.5). 
Please try it out and see if it solves the issue 👍
