### ISSUE TITLE
Incorrect configuration in documentation example

### ISSUE THREAD

**Issue by jcamilleri13** [poppa/sveltekit-svg#6]
As of the most recent versions of SvelteKit, any VIte plugins must be passed to a `vite` object in the Svelte config, e.g.
```js
kit: {
  ...
  vite: {
    plugins: [svg()]
  }
}
```

This is not currently reflected on the plugin documentation - you may want to update it.

Thanks for the super-useful plugin 😃

**Comment by poppa** [comment]
Thanks for the feedback 😊. I'm on vacation, hence the late response, but an update will come soon.
