### ISSUE TITLE
<SVGComponent> is not a valid SSR Component

### ISSUE THREAD

**Issue by binmalyi** [poppa/sveltekit-svg#65]
I've seen similar issues and followed up on them but they get me nowhere to the solution of the issue.

### `vite.config.js`
```ts
import { defineConfig } from 'vite';
import svg from "@poppanator/sveltekit-svg"
import { sveltekit } from '@sveltejs/kit/vite';

export default defineConfig({
	plugins: [sveltekit(), svg({includePaths: ["./static/svg/", "./src/lib/components/"]})],
	server: {
		fs: {
			allow: ["public/", "src/", "static/"]
		}
	}
});
```

### `svelte.config.js`
```ts
const config = {
	preprocess: vitePreprocess(),
	compilerOptions: {
		hydratable: true,
		immutable: true,
		css: "external"
	},
	kit: {
		adapter: adapter(),
		alias: {
			"public": "./public",
			"database": "./src/database",
			"utils": "./src/utils"
		},
		files: {
			appTemplate: "public/app.html"
		}
	}
};
```

### `Test.svelte`
```svelte
<script lang="ts">
    import Offline from "/svg/offline.svg?component";
</script>

<Offline />
```

### `package.json`
```json
{
"devDependencies": {
    "@sveltejs/adapter-auto": "^3.2.5",
    "@sveltejs/kit": "^2.5.28",
    "@sveltejs/package": "^2.3.5",
    "@sveltejs/vite-plugin-svelte": "^3.1.2",
    "pg": "^8.13.0",
    "publint": "^0.1.16",
    "svelte": "^4.2.19",
    "svelte-check": "^3.8.6",
    "typescript": "^5.6.2",
    "vite": "^5.4.7"
  }
}
```

**Comment by binmalyi** [comment]
I thought that would be taken care of internally by Svelte's asset handler like it normally does

**Comment by poppa** [comment]
> I thought that would be taken care of internally by Svelte's asset handler like it normally does

Can you please give an example?

**Comment by poppa** [comment]
If this is still a problem, feel free to re-open this issue

**Comment by m-dressler** [comment]
@poppa I just set up sveltekit-svg and got the same issue with the below:

```svelte
<script>
	import FavoriteIcon from '$lib/icons/favorite.svg?component';
</script>
<FavoriteIcon />
```

SVG is valid SVG syntax, path is correct.

**Comment by pascalpp** [comment]
> @poppa I just set up sveltekit-svg and got the same issue with the below:
> 
> ```svelte
> <script>
> 	import FavoriteIcon from '$lib/icons/favorite.svg?component';
> </script>
> <FavoriteIcon />
> ```
> 
> The below is working however:
> 
> ```svelte
> <script>
> 	import FavoriteIcon from '$lib/icons/favorite.svg?raw';
> </script>
> 
> {@html FavoriteIcon}
> ```

I think you just wanna render FavoriteIcon like any other svelte component: `<FavoriteIcon />`

**Comment by poppa** [comment]
@m-dressler I need more info than that! Svelte/Kit/Vite version, Svelte config, Vite config.

**Comment by m-dressler** [comment]
@poppa `@sveltejs/kit@2.5.6` (peer deps `@sveltejs/vite-plugin-svelte@^3.0.0`, `svelte: ^4.0.0 || ^5.0.0-next.0`, `vite@^5.0.3`)

Svelte config: 
```js
import adapter from '@sveltejs/adapter-node';
import preprocess from 'svelte-preprocess';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	preprocess: preprocess(),
	kit: { adapter: adapter({ origin: process.env.ORIGIN }) }
};

export default config;
```

Vite Config:
```js
import svg from '@poppanator/sveltekit-svg';
import { sveltekit } from '@sveltejs/kit/vite';
import tailwindcss from '@tailwindcss/vite';

/** @type {import('vite').UserConfig} */
const config = {
	plugins: [tailwindcss(), sveltekit(), svg()]
};

export default config;
```

**Comment by poppa** [comment]
Alright, that looks good to me. Unless you can provide me with a minimal sample project where the problem is reproducable, I'm afraid there isn't much I can to right now.
