### ISSUE TITLE
Does not work in svelte5

### ISSUE THREAD

**Issue by jakubdonovan** [poppa/sveltekit-svg#66]
Does not work in svelte5

>  Error: Your application, or one of its dependencies, imported from 'svelte/internal', which was a private module used by Svelte 4 components that no longer e
> xists in Svelte 5. It is not intended to be public API. If you're a library author and you used 'svelte/internal' deliberately, please raise an issue on http
> s://github.com/sveltejs/svelte/issues detailing your use case.
>     at eval (/Users/jakubdonovan/Documents/code/phuketkeyDeno/node_modules/.deno/svelte@5.0.0-next.264/node_modules/svelte/src/internal/index.js, <anonymous>
> :5:7)
>     at instantiateModule (file:///Users/jakubdonovan/Documents/code/phuketkeyDeno/node_modules/.deno/vite@5.4.8/node_modules/vite/dist/node/chunks/dep-CDnG8r
> E7.js:52915:11) {
>   stack: "Error: Your application, or one of its dependencies, imported from 'svelte/internal', which was a private module used by Svelte 4 components that n
> o longer exists in Svelte 5. It is not intended to be public API. If you're a library author and you used 'svelte/internal' deliberately, please raise an iss
> ue on https://github.com/sveltejs/svelte/issues detailing your use case.\n" +
>     "    at eval (/Users/jakubdonovan/Documents/code/phuketkeyDeno/node_modules/.deno/svelte@5.0.0-next.264/node_modules/svelte/src/internal/index.js, <anony
> mous>:5:7)\n" +
>     "    at instantiateModule (file:///Users/jakubdonovan/Documents/code/phuketkeyDeno/node_modules/.deno/vite@5.4.8/node_modules/vite/dist/node/chunks/dep-C
> DnG8rE7.js:52915:11)"
>

**Comment by poppa** [comment]
Have you tried the [Svelte5 version](https://github.com/poppa/sveltekit-svg/issues/53) of this plugin?

**Comment by jakubdonovan** [comment]
> Have you tried the [Svelte5 version](https://github.com/poppa/sveltekit-svg/issues/53) of this plugin?

I didn't realize that there was a svelte5 version. I just tried it and it worked. Thanks
